export const campaignData= [
    { 'id': 1,name:'ABC', img: './assets/media/products/image1.jpg',createdDate: '2020/11/19',description:'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs.',style:'Style Z',product:'0', emailsenton: '2012/11/10',  senthistory: '0', note:'8', linesliceurl:"xyz.com"},
    { 'id': 2,name:'PQR', img: '/assets/media/products/image2.jpg',createdDate: '2020/11/19',description:'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs.',style:'Regular',product:'3', emailsenton: '2015/11/11',  senthistory: '0', note:'8', linesliceurl:"xyz.com" },
    { 'id': 3,name:'XYZ', img: '/assets/media/products/image3.jpg',createdDate: '2020/11/19',description:'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs.',style:'Style Z',product:'5', emailsenton: '2017/11/12',  senthistory: '0', note:'8', linesliceurl:"xyz.com" },
    { 'id': 4,name:'ABC', img: '/assets/media/products/image4.jpg',createdDate: '2020/11/19',description:'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs.',style:'Regular',product:'1', emailsenton: '2010/11/13',  senthistory: '0', note:'8', linesliceurl:"xyz.com" },
    { 'id': 5,name:'PQR', img: '/assets/media/products/image3.jpg',createdDate: '2020/11/19',description:'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs.',style:'Style Z',product:'1', emailsenton: '2013/11/14',  senthistory: '7', note:'8', linesliceurl:"xyz.com" },
    { 'id': 6,name:'XYZ', img: '/assets/media/products/image6.jpg',createdDate: '2020/11/19',description:'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs.',style:'Regular',product:'5', emailsenton: '2014/11/15',  senthistory: '6', note:'8', linesliceurl:"xyz.com" },
    { 'id': 7,name:'ASD', img: '/assets/media/products/image7.jpg',createdDate: '2020/11/19',description:'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs.',style:'Style Z',product:'9', emailsenton: '2017/11/16',  senthistory: '2', note:'8', linesliceurl:"xyz.com"},
    { 'id': 8,name:'ABC', img: '/assets/media/products/image8.jpg',createdDate: '2020/11/19',description:'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs.',style:'Style Z',product:'0', emailsenton: '2019/11/17',  senthistory: '1', note:'8', linesliceurl:"xyz.com" },
    { 'id': 9,name:'TEST', img: '/assets/media/products/image9.jpg',createdDate: '2020/11/19',description:'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs.',style:'Style Z',product:'3', emailsenton: '2021/11/01',  senthistory: '5', note:'8', linesliceurl:"xyz.com" },
    { 'id': 10,name:'ABC', img: '/assets/media/products/image10.jpg',createdDate: '2020/11/19',description:'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs.',style:'Style Z',product:'5', emailsenton: '2020/11/19',  senthistory: '8', note:'8', linesliceurl:"xyz.com"},
]